# ファイルの目的がわかるように記載
name: Notify Mattermost on PR to develop

# 処理の起動条件を定義
on:
  # プルリクエストがクローズ
  pull_request:
    types: [closed]
    # ターゲットブランチがdevelop
    branches:
      - develop

# ジョブの定義
jobs:

  # 「notify」はジョブの名前（なんでもOK）
  notify:

    # GitHubが提供する最新のUbuntu環境（仮想マシン）上で実行
    runs-on: ubuntu-latest

    # 処理の中身を定義
    steps:
      - name: Send message to Mattermost
        run: |
          curl -X POST -H 'Content-Type: applivation/json' \
            -d '{
              "test": "@all\nプルリクエストがマージされました！\n●リポジトリ: '${{ github.repository }}'\n●PRタイトル: \"${{ github.event.pull_request.title }}\"\n●作成者: ${{ github.event.pull_request.user.login }}\n●URL: ${{github.event.pull_request.html_url }}"
            }' ${{ secrets.https://chat.raretech.site/hooks/y9maqimxapdybrg65p3hu8ix7o }}